CREATE TABLE `a_stock_market_price_day` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `date` varchar(50) NOT NULL,
  `time` varchar(50) DEFAULT NULL,
  `open` double NOT NULL,
  `high` double NOT NULL,
  `low` double NOT NULL,
  `close` double NOT NULL,
  `preclose` double NOT NULL,
  `volume` bigint(10) NOT NULL,
  `amount` double NOT NULL,
  `turn` double DEFAULT 0.0,
  `adjustflag` tinyint(2) DEFAULT NULL,
  `tradestatus` tinyint(2) DEFAULT NULL,
  `pctChg` double DEFAULT NULL,
  `peTTM` double DEFAULT NULL,
  `psTTM` double DEFAULT NULL,
  `pcfNcfTTM` double DEFAULT NULL,
  `pbMRQ` double DEFAULT NULL,
  `isST` tinyint(2) DEFAULT NULL,
  `creation_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx`(`code`, `name`, `date`),
  KEY `idx_key` (`code`, `name`, `date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

